//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOFSales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Product_Id { get; set; }
        public string ProductQuantity { get; set; }
        public string ProdutName { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public string Barcode { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> category_Id { get; set; }
        public Nullable<int> Model_Id { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ColorId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ProductModel ProductModel { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual ColorType ColorType { get; set; }
    }
}
