//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOFSales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOut
    {
        public int StockOut_id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string AmountStockOut { get; set; }
        public Nullable<System.DateTime> DateStockOut { get; set; }
        public Nullable<System.DateTime> UpdateStockOutDate { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
