//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOFSales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockIn
    {
        public int StockIn_Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CurrentQuantityBalance { get; set; }
        public string AmountStockIn { get; set; }
        public string SupplierName { get; set; }
        public string StockType { get; set; }
        public Nullable<System.DateTime> DateStock { get; set; }
        public string Description { get; set; }
        public string TotalBalance { get; set; }
        public string ProductName { get; set; }
        public string Color_Id { get; set; }
        public string Color { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
